# Generated by Django 2.2.3 on 2019-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, upload_to='machines', verbose_name='Фото оборудования'),
        ),
    ]
